FROM node:current-alpine as builder
WORKDIR /apk
RUN apk add --no-cache postgresql-client

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npx prisma generate

COPY wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh

EXPOSE 3000

CMD ["sh", "-c", "/wait-for-db.sh && npx prisma db push && npx prisma db execute --file ./prisma/seed.sql && npm run start:dev"]
