FROM node:current-alpine as builder
WORKDIR /apk
RUN apk add --no-cache postgresql-client

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV DATABASE_URL="postgresql://placeholder:placeholder@localhost:5432/placeholder"
RUN npx prisma generate

RUN npm run build

CMD ["sh", "-c", "until pg_isready -h \"$DB_HOST\" -p \"$DB_PORT\" -U myuser -d mydb; do echo 'Waiting for database...'; sleep 2; done && npx prisma migrate deploy && npx prisma db execute --file ./prisma/seed.sql && npm run start"]
