-- Create enum type
CREATE TYPE "user_role" AS ENUM (
  'admin',
  'user'
);

-- Tables
CREATE TABLE "project" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "call_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(50) UNIQUE NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(50),
  "role" user_role NOT NULL,
  "otp" varchar(6),
  "otpExpiry" timestamp,
  "jwtToken" text
);

CREATE TABLE "user_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" int,
  "start_time" timestamp NOT NULL DEFAULT (now()),
  "duration" int,
  "is_active" boolean
);

CREATE TABLE "owner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "attempt_count" int,
  "last_dialed_at" timestamp,
  "next_dial_at" timestamp
);

-- Fixed: removed incorrect primary key and foreign key on "number",
-- added proper "owner_id" column and FK
CREATE TABLE "numbers" (
  "number" char(13),
  "owner_id" bigint
);

-- Fixed: changed "string" to "varchar(60)" for PostgreSQL compatibility
CREATE TABLE "owner_info" (
  "key" varchar(60),
  "owner_id" bigint,
  "value" varchar(60)
);

-- Fixed: "status" column type changed to INT to match FK to call_status.id
CREATE TABLE "call_detail_record" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint,
  "agent_id" int,
  "status" int,
  "time" timestamp NOT NULL,
  "duration" int,
  "agent_notes" text
);

COMMENT ON COLUMN "user_log"."duration" IS 'Calculated in seconds once status changes/ends';

-- Foreign keys
ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "project_call_detail_record" (
  "project_id" int,
  "call_detail_record_id" bigint,
  PRIMARY KEY ("project_id", "call_detail_record_id")
);

ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("call_detail_record_id") REFERENCES "call_detail_record" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_log" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "owner_project" (
  "owner_id" bigint,
  "project_id" int,
  PRIMARY KEY ("owner_id", "project_id")
);

ALTER TABLE "owner_project" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "owner_project" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("status") REFERENCES "call_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Fixed: FK on numbers now references owner_id column
ALTER TABLE "numbers" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "owner_info" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- ================================================
-- Dummy data inserts (10+ rows per table)
-- ================================================

-- Fixed: single BEGIN, removed duplicate
BEGIN;
SET CONSTRAINTS ALL DEFERRED;

-- call_status (with explicit IDs to match references)
INSERT INTO "call_status" ("id", "name")
VALUES
  (1, 'new'),
  (2, 'contacted'),
  (3, 'not_interested'),
  (4, 'busy'),
  (5, 'callback');

-- project (10 items)
INSERT INTO "project" ("id", "name", "description")
VALUES
  (1, 'Summer Sales Campaign', 'Outbound sales campaign for summer product line targeting warm leads'),
  (2, 'Customer Feedback Survey', 'Quarterly customer satisfaction survey for existing clients'),
  (3, 'Lead Generation Q3', 'Cold calling campaign to generate new leads for Q3 pipeline'),
  (4, 'Appointment Setting', 'Setting up demos and meetings with potential enterprise clients'),
  (5, 'Debt Collection', 'Follow-up calls for outstanding payments and payment plan arrangements'),
  (6, 'Market Research', 'Gathering market intelligence and competitor analysis data'),
  (7, 'Holiday Promotion', 'Promotional campaign for holiday season special offers and discounts'),
  (8, 'Product Launch Outreach', 'Introducing new product line to existing and potential customers'),
  (9, 'Customer Retention', 'Win-back campaign for churned customers with special offers'),
  (10, 'Event Registration', 'Inviting clients to annual conference and managing RSVPs');

-- user (12 items) – column name now matches table definition
INSERT INTO "user" ("id", "email", "phone_number", "password_hash", "name", "role", "otp", "otpExpiry", "jwtToken")
VALUES
  (1, 'admin_john@example.com', '+15551234567', '$2b$12$LJ3m4ys3Lk0TSwHCpWqFCOHfQdDlDjBq7V3P9M8xA4z8KqWxYz5Oa', 'John Smith', 'admin', NULL, NULL, NULL),
  (2, 'agent_sarah@example.com', '+15552345678', '$2b$12$Kd8xPq2MnR7Ts5YbWvZtEe9XcBnMkL4pH6JfG8hR3aC5dNsVqWyBx', 'Sarah Johnson', 'user', NULL, NULL, NULL),
  (3, 'agent_mike@example.com', '+15553456789', '$2b$12$Ab4cFg7HkL0PqRsUvWxYz2CdEfGhJkMn3OpQr5StUvWxYzAbCdEfG', 'Mike Williams', 'user', NULL, NULL, NULL),
  (4, 'agent_lisa@example.com', '+15554567890', '$2b$12$XyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVw', 'Lisa Brown', 'user', NULL, NULL, NULL),
  (5, 'admin_emma@example.com', '+15555678901', '$2b$12$MnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKl', 'Emma Davis', 'admin', NULL, NULL, NULL),
  (6, 'agent_tom@example.com', '+15556789012', '$2b$12$DeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBc', 'Tom Wilson', 'user', NULL, NULL, NULL),
  (7, 'agent_amy@example.com', '+15557890123', '$2b$12$StUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQr', 'Amy Taylor', 'user', NULL, NULL, NULL),
  (8, 'agent_james@example.com', '+15558901234', '$2b$12$EfGhIjKlMnOpQrStUvWxYzAbCdEfGhIjKlMnOpQrStUvWxYzAbCdE', 'James Anderson', 'user', NULL, NULL, NULL),
  (9, 'agent_rachel@example.com', '+15559012345', '$2b$12$VwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuV', 'Rachel Martinez', 'user', NULL, NULL, NULL),
  (10, 'agent_david@example.com', '+15550123456', '$2b$12$BcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZa', 'David Thomas', 'user', NULL, NULL, NULL),
  (11, 'agent_karen@example.com', '+15551234560', '$2b$12$PqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoP', 'Karen White', 'user', NULL, NULL, NULL),
  (12, 'admin_chris@example.com', '+15552345671', '$2b$12$JkLmNoPqRsTuVwXyZaBcDeFgHiJkLmNoPqRsTuVwXyZaBcDeFgHi', 'Chris Lee', 'admin', NULL, NULL, NULL);

-- owner (12 items)
INSERT INTO "owner" ("id", "name", "attempt_count", "last_dialed_at", "next_dial_at")
VALUES
  (1, 'Robert Chen', 3, '2026-06-30 14:30:00', '2026-07-03 10:00:00'),
  (2, 'Maria Garcia', 1, '2026-07-01 09:15:00', '2026-07-05 14:00:00'),
  (3, 'Kevin O''Brien', 5, '2026-07-01 16:45:00', '2026-07-02 11:30:00'),
  (4, 'Jennifer Taylor', 0, NULL, '2026-07-04 09:00:00'),
  (5, 'Daniel Kim', 2, '2026-06-29 10:20:00', '2026-07-06 15:00:00'),
  (6, 'Patricia Lopez', 4, '2026-07-02 08:30:00', '2026-07-03 13:45:00'),
  (7, 'William Turner', 1, '2026-06-28 11:00:00', '2026-07-02 10:00:00'),
  (8, 'Elizabeth Adams', 0, NULL, '2026-07-05 16:30:00'),
  (9, 'Michael Scott', 6, '2026-07-01 13:20:00', '2026-07-03 09:15:00'),
  (10, 'Barbara Wilson', 2, '2026-06-30 15:10:00', '2026-07-07 11:00:00'),
  (11, 'Richard Moore', 3, '2026-07-02 10:05:00', '2026-07-04 14:20:00'),
  (12, 'Susan Clark', 1, '2026-06-27 12:45:00', '2026-07-02 08:30:00');

-- numbers (11 items)
INSERT INTO "numbers" ("number", "owner_id")
VALUES
  ('+15551112222', 1),
  ('+15552223342', 1),
  ('+15552223333', 2),
  ('+15553334444', 3),
  ('+15554445555', 4),
  ('+15555556666', 5),
  ('+15556667777', 6),
  ('+15557778888', 7),
  ('+15558889999', 8),
  ('+15559990000', 9),
  ('+15550001111', 10);

-- owner_info (12 items)
INSERT INTO "owner_info" ("key", "owner_id", "value")
VALUES
  ('email', 1, 'robert.chen@email.com'),
  ('company', 1, 'TechCorp Inc'),
  ('email', 2, 'maria.garcia@email.com'),
  ('preferred_time', 2, 'morning'),
  ('email', 3, 'kevin.obrien@email.com'),
  ('notes', 3, 'Prefers calls after 4 PM'),
  ('email', 4, 'jennifer.taylor@email.com'),
  ('email', 5, 'daniel.kim@email.com'),
  ('company', 5, 'Kim Enterprises'),
  ('email', 6, 'patricia.lopez@email.com'),
  ('source', 6, 'Website referral'),
  ('email', 7, 'william.turner@email.com');

-- user_log (12 items)
INSERT INTO "user_log" ("id", "agent_id", "start_time", "duration", "is_active")
VALUES
  (1, 2, '2026-07-01 08:00:00', 14400, true),
  (2, 3, '2026-07-01 08:05:00', 10800, false),
  (3, 4, '2026-07-01 08:30:00', 25200, true),
  (4, 2, '2026-07-02 08:02:00', 7200, true),
  (5, 6, '2026-07-02 08:10:00', 18000, false),
  (6, 7, '2026-07-02 09:00:00', 14400, true),
  (7, 8, '2026-07-02 08:15:00', 3600, false),
  (8, 3, '2026-07-03 08:00:00', NULL, true),
  (9, 4, '2026-07-03 08:45:00', 9000, false),
  (10, 9, '2026-07-03 09:00:00', NULL, true),
  (11, 10, '2026-07-03 08:30:00', 7200, false),
  (12, 11, '2026-07-03 10:00:00', NULL, true);

-- call_detail_record (15 items) – status IDs match call_status
INSERT INTO "call_detail_record" ("id", "owner_id", "agent_id", "status", "time", "duration", "agent_notes")
VALUES
  (1, 1, 2, 2, '2026-06-30 14:30:00', 320, 'Customer interested in product upgrade. Sending brochure.'),
  (2, 2, 3, 2, '2026-07-01 09:15:00', 180, 'Discussed new pricing options. Will review and call back.'),
  (3, 3, 4, 3, '2026-07-01 16:45:00', 45, 'Not interested at this time. Remove from list.'),
  (4, 5, 6, 4, '2026-06-29 10:20:00', 10, 'Line busy. Will retry later.'),
  (5, 6, 7, 2, '2026-07-02 08:30:00', 600, 'Lengthy discussion about service offerings. Very interested.'),
  (6, 7, 8, 1, '2026-06-28 11:00:00', 0, 'No answer. Left voicemail.'),
  (7, 9, 2, 5, '2026-07-01 13:20:00', 240, 'Wants callback next week when budget is finalized.'),
  (8, 10, 3, 2, '2026-06-30 15:10:00', 420, 'Scheduled demo for next Tuesday at 2 PM.'),
  (9, 11, 4, 3, '2026-07-02 10:05:00', 90, 'Asked to be removed from calling list.'),
  (10, 12, 6, 1, '2026-06-27 12:45:00', 0, 'Wrong number.'),
  (11, 1, 9, 2, '2026-07-02 11:20:00', 280, 'Follow-up call. Customer has questions about contract terms.'),
  (12, 3, 10, 4, '2026-07-02 14:00:00', 15, 'Voicemail box full.'),
  (13, 4, 11, 2, '2026-07-03 09:45:00', 350, 'First contact. Explained services. Positive response.'),
  (14, 8, 7, 1, '2026-07-03 10:30:00', 0, 'Ringing, no answer.'),
  (15, 2, 2, 2, '2026-07-03 11:15:00', 195, 'Customer ready to proceed. Processing order.');

-- project_call_detail_record (15 items)
INSERT INTO "project_call_detail_record" ("project_id", "call_detail_record_id")
VALUES
  (1, 1), (1, 5), (1, 8), (1, 13),
  (2, 2), (2, 6), (2, 11),
  (3, 3), (3, 9), (3, 14),
  (4, 4), (4, 7), (4, 15),
  (5, 10), (6, 12);

-- owner_project (15 items)
INSERT INTO "owner_project" ("owner_id", "project_id")
VALUES
  (1, 1), (1, 4),
  (2, 1), (2, 2),
  (3, 3), (3, 5),
  (4, 1), (4, 8),
  (5, 3), (5, 7),
  (6, 2), (6, 6),
  (7, 4), (7, 9),
  (8, 10);

SET CONSTRAINTS ALL IMMEDIATE;
COMMIT;
-- 1. Row counts: ensure each table has at least 10 rows
SELECT 'project' AS table_name, COUNT(*) FROM project
UNION ALL SELECT 'user', COUNT(*) FROM "user"
UNION ALL SELECT 'owner', COUNT(*) FROM owner
UNION ALL SELECT 'numbers', COUNT(*) FROM numbers
UNION ALL SELECT 'owner_info', COUNT(*) FROM owner_info
UNION ALL SELECT 'user_log', COUNT(*) FROM user_log
UNION ALL SELECT 'call_detail_record', COUNT(*) FROM call_detail_record
UNION ALL SELECT 'project_call_detail_record', COUNT(*) FROM project_call_detail_record
UNION ALL SELECT 'owner_project', COUNT(*) FROM owner_project
UNION ALL SELECT 'call_status', COUNT(*) FROM call_status;

-- 2. All call records with agent name, owner name, and status label
SELECT
  cdr.id,
  u.name AS agent_name,
  o.name AS owner_name,
  cs.name AS call_status,
  cdr.time,
  cdr.duration,
  cdr.agent_notes
FROM call_detail_record cdr
JOIN "user" u ON cdr.agent_id = u.id
JOIN owner o ON cdr.owner_id = o.id
JOIN call_status cs ON cdr.status = cs.id
ORDER BY cdr.time DESC;

-- 3. Which call statuses are used and how many calls per status
SELECT cs.name, COUNT(*) AS total_calls
FROM call_detail_record cdr
JOIN call_status cs ON cdr.status = cs.id
GROUP BY cs.name
ORDER BY total_calls DESC;

-- 4. Agents and their total calls / total call duration
SELECT
  u.name AS agent_name,
  COUNT(cdr.id) AS calls_handled,
  COALESCE(SUM(cdr.duration), 0) AS total_duration_seconds
FROM "user" u
LEFT JOIN call_detail_record cdr ON u.id = cdr.agent_id
WHERE u.role = 'user'   -- only agents (non‑admins)
GROUP BY u.id, u.name
ORDER BY calls_handled DESC;

-- 5. Owners with their phone numbers (shows the numbers table link)
SELECT o.name AS owner_name, n.number
FROM owner o
JOIN numbers n ON n.owner_id = o.id
ORDER BY o.name, n.number;

-- 6. Owners with extra info (key‑value pairs)
SELECT o.name, oi.key, oi.value
FROM owner o
JOIN owner_info oi ON oi.owner_id = o.id
ORDER BY o.name, oi.key;

-- 7. Which projects does each owner belong to?
SELECT o.name AS owner_name, p.name AS project_name
FROM owner o
JOIN owner_project op ON o.id = op.owner_id
JOIN project p ON op.project_id = p.id
ORDER BY o.name, p.name;

-- 8. Which projects are associated with each call?
SELECT
  cdr.id AS call_id,
  p.name AS project_name,
  o.name AS owner_name,
  u.name AS agent_name
FROM call_detail_record cdr
JOIN project_call_detail_record pcdr ON cdr.id = pcdr.call_detail_record_id
JOIN project p ON pcdr.project_id = p.id
JOIN owner o ON cdr.owner_id = o.id
JOIN "user" u ON cdr.agent_id = u.id
ORDER BY cdr.time;

-- 9. Check that no orphan rows exist (foreign key integrity)
-- These should all return 0 rows.

-- call_detail_record with invalid owner
SELECT cdr.id FROM call_detail_record cdr
LEFT JOIN owner o ON cdr.owner_id = o.id WHERE o.id IS NULL;

-- call_detail_record with invalid agent
SELECT cdr.id FROM call_detail_record cdr
LEFT JOIN "user" u ON cdr.agent_id = u.id WHERE u.id IS NULL;

-- call_detail_record with invalid status
SELECT cdr.id FROM call_detail_record cdr
LEFT JOIN call_status cs ON cdr.status = cs.id WHERE cs.id IS NULL;

-- numbers with invalid owner
SELECT * FROM numbers n
LEFT JOIN owner o ON n.owner_id = o.id WHERE o.id IS NULL;

-- owner_info with invalid owner
SELECT * FROM owner_info oi
LEFT JOIN owner o ON oi.owner_id = o.id WHERE o.id IS NULL;

-- user_log with invalid agent
SELECT * FROM user_log ul
LEFT JOIN "user" u ON ul.agent_id = u.id WHERE u.id IS NULL;

-- project_call_detail_record referencing missing project or CDR
SELECT * FROM project_call_detail_record pcdr
LEFT JOIN project p ON pcdr.project_id = p.id WHERE p.id IS NULL;
SELECT * FROM project_call_detail_record pcdr
LEFT JOIN call_detail_record cdr ON pcdr.call_detail_record_id = cdr.id WHERE cdr.id IS NULL;

-- owner_project referencing missing owner or project
SELECT * FROM owner_project op
LEFT JOIN owner o ON op.owner_id = o.id WHERE o.id IS NULL;
SELECT * FROM owner_project op
LEFT JOIN project p ON op.project_id = p.id WHERE p.id IS NULL;

-- 10. User log entries with agent name and active status
SELECT ul.id, u.name AS agent_name, ul.start_time, ul.duration, ul.is_active
FROM user_log ul
JOIN "user" u ON ul.agent_id = u.id
ORDER BY ul.start_time DESC;

-- 11. Summary: owners with attempt_count and next_dial_at
SELECT name, attempt_count, last_dialed_at, next_dial_at
FROM owner
WHERE next_dial_at IS NOT NULL
ORDER BY next_dial_at;