-- Create enum type
CREATE TYPE "user_role" AS ENUM (
  'admin',
  'user'
);

-- Tables
CREATE TABLE "project" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "call_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(50) UNIQUE NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(50),
  "role" user_role NOT NULL,
  "otp" varchar(6),
  "otpExpiry" timestamp,
  "jwtToken" text
);

CREATE TABLE "user_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" int,
  "start_time" timestamp NOT NULL DEFAULT (now()),
  "duration" int,
  "is_active" boolean
);

CREATE TABLE "owner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "attempt_count" int,
  "last_dialed_at" timestamp,
  "next_dial_at" timestamp
);

-- Fixed: removed incorrect primary key and foreign key on "number",
-- added proper "owner_id" column and FK
CREATE TABLE "numbers" (
  "number" char(13),
  "owner_id" bigint
);

-- Fixed: changed "string" to "varchar(60)" for PostgreSQL compatibility
CREATE TABLE "owner_info" (
  "key" varchar(60),
  "owner_id" bigint,
  "value" varchar(60)
);

-- Fixed: "status" column type changed to INT to match FK to call_status.id
CREATE TABLE "call_detail_record" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint,
  "agent_id" int,
  "status" int,
  "time" timestamp NOT NULL,
  "duration" int,
  "agent_notes" text
);

COMMENT ON COLUMN "user_log"."duration" IS 'Calculated in seconds once status changes/ends';

-- Foreign keys
ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "project_call_detail_record" (
  "project_id" int,
  "call_detail_record_id" bigint,
  PRIMARY KEY ("project_id", "call_detail_record_id")
);

ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("call_detail_record_id") REFERENCES "call_detail_record" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_log" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "owner_project" (
  "owner_id" bigint,
  "project_id" int,
  PRIMARY KEY ("owner_id", "project_id")
);

ALTER TABLE "owner_project" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "owner_project" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("status") REFERENCES "call_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Fixed: FK on numbers now references owner_id column
ALTER TABLE "numbers" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "owner_info" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;
