CREATE TYPE "user_role" AS ENUM (
  'admin',
  'user'
);

CREATE TABLE "project" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "call_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20)
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(50),
  "role" user_role NOT NULL
);

CREATE TABLE "user_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" int,
  "start_time" timestamp NOT NULL DEFAULT (now()),
  "duration" int,
  "is_active" boolean
);

CREATE TABLE "owner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "attempt_count" int,
  "last_dialed_at" timestamp,
  "next_dial_at" timestamp
);

CREATE TABLE "numbers" (
  "number" char(13) PRIMARY KEY
);

CREATE TABLE "call_detail_record" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint,
  "agent_id" int,
  "status" call_status,
  "time" timestamp NOT NULL,
  "duration" int,
  "agent_notes" text
);

COMMENT ON COLUMN "user_log"."duration" IS 'Calculated in seconds once status changes/ends';

ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "project_call_detail_record" (
  "project_id" int,
  "call_detail_record_id" bigint,
  PRIMARY KEY ("project_id", "call_detail_record_id")
);

ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_call_detail_record" ADD FOREIGN KEY ("call_detail_record_id") REFERENCES "call_detail_record" ("id") DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE "user_log" ADD FOREIGN KEY ("agent_id") REFERENCES "user" ("id") DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE "owner_project" (
  "owner_id" bigint,
  "project_id" int,
  PRIMARY KEY ("owner_id", "project_id")
);

ALTER TABLE "owner_project" ADD FOREIGN KEY ("owner_id") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "owner_project" ADD FOREIGN KEY ("project_id") REFERENCES "project" ("id") DEFERRABLE INITIALLY IMMEDIATE;


ALTER TABLE "call_detail_record" ADD FOREIGN KEY ("status") REFERENCES "call_status" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "numbers" ADD FOREIGN KEY ("number") REFERENCES "owner" ("id") DEFERRABLE INITIALLY IMMEDIATE;

-- Defer constraint checking for INSERT
BEGIN;
SET CONSTRAINTS ALL DEFERRED;

INSERT INTO "call_status" ("id", "name")
VALUES
  (1, 'new'),
  (2, 'contacted'),
  (3, 'not_interested'),
  (4, 'busy'),
  (5, 'callback');

SET CONSTRAINTS ALL IMMEDIATE;
COMMIT;