CREATE TYPE "user_role" AS ENUM (
  'admin',
  'user'
);

CREATE TABLE "project" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "description" text
);

CREATE TABLE "call_status" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(20) NOT NULL
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "phone_number" varchar(20) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(50),
  "role" user_role NOT NULL
);

CREATE TABLE "user_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "agent_id" int NOT NULL,
  "start_time" timestamp NOT NULL DEFAULT now(),
  "duration" int,
  "is_active" boolean NOT NULL DEFAULT true,
  FOREIGN KEY ("agent_id") REFERENCES "user" ("id")
);
COMMENT ON COLUMN "user_log"."duration" IS 'Calculated in seconds once session ends';

CREATE TABLE "owner" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50),
  "attempt_count" int NOT NULL DEFAULT 0,
  "last_dialed_at" timestamp,
  "next_dial_at" timestamp
);

CREATE TABLE "owner_number" (
  "number" char(13) PRIMARY KEY,
  "owner_id" bigint NOT NULL,
  FOREIGN KEY ("owner_id") REFERENCES "owner" ("id")
);

CREATE TABLE "owner_project" (
  "owner_id" bigint,
  "project_id" int,
  PRIMARY KEY ("owner_id", "project_id"),
  FOREIGN KEY ("owner_id") REFERENCES "owner" ("id"),
  FOREIGN KEY ("project_id") REFERENCES "project" ("id")
);

CREATE TABLE "call_detail_record" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "owner_id" bigint NOT NULL,
  "agent_id" int NOT NULL,
  "project_id" int NOT NULL,              -- which project this call was made under
  "status_id" int NOT NULL,
  "start_time" timestamp NOT NULL,
  "answer_time" timestamp,                -- null = never answered
  "end_time" timestamp NOT NULL,
  "duration" int,                         -- talk time in seconds (end_time - answer_time)
  "agent_notes" text,
  FOREIGN KEY ("owner_id") REFERENCES "owner" ("id"),
  FOREIGN KEY ("agent_id") REFERENCES "user" ("id"),
  FOREIGN KEY ("project_id") REFERENCES "project" ("id"),
  FOREIGN KEY ("status_id") REFERENCES "call_status" ("id")
);

INSERT INTO "call_status" ("id", "name") VALUES
  (1, 'new'),
  (2, 'contacted'),
  (3, 'not_interested'),
  (4, 'busy'),
  (5, 'callback');
